Repository wanted-running-sheep/wanted-pre-onboarding-fe, pull requests merged in 2022-07, with the labels that each got.

#3 ✨ feat: 로그인 페이지 구현
  .gitignore
  package-lock.json
  package.json
  src/App.js
  src/assets/images/InstagramLogo.svg
  src/components/LoginForm.jsx
  src/components/LoginInput.jsx
  src/context/AuthContext.js
  src/index.js
  src/pages/Login.jsx
  src/util/validation.js
Labels: 🕹️ 기능, 📱 UI

#2 ✨ feat: 메인페이지 구현
  .gitignore
  package-lock.json
  package.json
  public/data/feed.json
  src/App.js
  src/api/api.js
  src/components/Feed.jsx
  src/components/NavigationBar.jsx
  src/hooks/useFeed.js
  src/index.js
  src/pages/Main.jsx
Labels: 🕹️ 기능, 📱 UI

#4 💄 style: 네비게이션 UI 추가
  src/components/NavigationBar.jsx
  src/index.js
  src/styles/theme.js
Labels: 🕹️ 기능, 📱 UI

#5 📝 docs: Readme 수정
  README.md
Labels: 📖 문서

#6 ♻️ refactor: theme 정의하여 공통 css 컨벤션 사용하도록 수정
  src/components/LoginForm.jsx
  src/components/LoginInput.jsx
  src/components/NavigationBar.jsx
  src/pages/Login.jsx
  src/styles/theme.js
Labels: ⬆️ 리팩토링, 📱 UI

#7 💄 style: 피드 UI 구현 및 로직 추가
  package-lock.json
  package.json
  src/components/Feed.jsx
  src/pages/Main.jsx
Labels: 🕹️ 기능, 📱 UI

#8 ♻️ refactor: App에 있는 Router 분리
  src/App.js
  src/components/Router.jsx
Labels: ⬆️ 리팩토링
